SELECT * FROM retencao_por_mes
SELECT * FROM retencao_por_trimestre

--LIMPEZA DE TABELAS

--Excluindo Colunas da tabela retencao_por_mes

ALTER TABLE retencao_por_mes DROP COLUMN [1 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [2 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [3 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [4 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [5 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [6 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [7 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [8 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [9 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [10 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [11 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [12 2019]
ALTER TABLE retencao_por_mes DROP COLUMN [1 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [2 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [3 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [4 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [5 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [6 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [7 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [8 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [9 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [10 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [11 2020]
ALTER TABLE retencao_por_mes DROP COLUMN [12 2020]

--Excluindo Colunas da tabela retencao_por_trimestre

ALTER TABLE retencao_por_trimestre DROP COLUMN [2019-T1]
ALTER TABLE retencao_por_trimestre DROP COLUMN [2019-T2]
ALTER TABLE retencao_por_trimestre DROP COLUMN [2019-T3]
ALTER TABLE retencao_por_trimestre DROP COLUMN [2019-T4]
ALTER TABLE retencao_por_trimestre DROP COLUMN [2020-T1]
ALTER TABLE retencao_por_trimestre DROP COLUMN [2020-T2]
ALTER TABLE retencao_por_trimestre DROP COLUMN [2020-T3]
ALTER TABLE retencao_por_trimestre DROP COLUMN [2020-T4]


--TABELAS ALTERADAS

SELECT * FROM retencao_por_mes
SELECT * FROM retencao_por_trimestre

--CRIAÇÃO DE TABELAS DE PRODUÇÃO

CREATE TABLE TB_ACT_RETENCAO_POR_MES
(
CLIENTE NVARCHAR(150),
ESTADO_CLIENTE NVARCHAR(150),
MES_REGISTRO NVARCHAR(50),
MES_DE_ABANDONO NVARCHAR(50),
)

INSERT INTO [dbo].[TB_ACT_RETENCAO_POR_MES]
SELECT * FROM retencao_por_mes

CREATE TABLE TB_ACT_RETENCAO_POR_TRIMESTRE
(
CLIENTE NVARCHAR(150),
ESTADO_CLIENTE NVARCHAR(150),
MES_REGISTRO NVARCHAR(50),
MES_DE_ABANDONO NVARCHAR(50),
)

INSERT INTO TB_ACT_RETENCAO_POR_TRIMESTRE
SELECT * FROM retencao_por_trimestre

--TABELAS ATUALIZADAS

SELECT * FROM TB_ACT_RETENCAO_POR_MES
SELECT * FROM TB_ACT_RETENCAO_POR_TRIMESTRE

--CONSULTAS
--NUMERO DE CLIENTES ATIVOS X NUMERO DE CLIENTES INATIVOS
SELECT COUNT(CLIENTE) AS NUM_CLIENTES,ESTADO_CLIENTE
FROM TB_ACT_RETENCAO_POR_MES
GROUP BY ESTADO_CLIENTE

--SUBSTITUINDO VALORES VAZIOS POR NULOS
UPDATE TB_ACT_RETENCAO_POR_MES
SET MES_DE_ABANDONO = NULL
WHERE MES_DE_ABANDONO = ''

UPDATE TB_ACT_RETENCAO_POR_TRIMESTRE
SET MES_DE_ABANDONO =NULL
WHERE MES_DE_ABANDONO = ''

--CONSULTA DOS CLIENTES INATIVOS
SELECT * FROM TB_ACT_RETENCAO_POR_MES
WHERE MES_DE_ABANDONO IS NOT NULL

SELECT * FROM TB_ACT_RETENCAO_POR_TRIMESTRE
WHERE MES_DE_ABANDONO IS NOT NULL

--NUMERO DE ABANDONOS POR MÊS
SELECT MES_DE_ABANDONO, COUNT(CLIENTE) AS NUM_DE_ABANDONOS
FROM TB_ACT_RETENCAO_POR_MES
WHERE MES_DE_ABANDONO IS NOT NULL
GROUP BY MES_DE_ABANDONO
ORDER BY NUM_DE_ABANDONOS DESC

SELECT MES_DE_ABANDONO, COUNT(CLIENTE) AS NUM_DE_ABANDONOS
FROM TB_ACT_RETENCAO_POR_TRIMESTRE
WHERE MES_DE_ABANDONO IS NOT NULL
GROUP BY MES_DE_ABANDONO
ORDER BY NUM_DE_ABANDONOS DESC

--NUMERO DE REGISTROS POR MÊS
SELECT MES_REGISTRO, COUNT(CLIENTE) AS NUM_DE_REGISTROS
FROM TB_ACT_RETENCAO_POR_MES
WHERE MES_REGISTRO IS NOT NULL
GROUP BY MES_REGISTRO
ORDER BY NUM_DE_REGISTROS DESC

SELECT MES_REGISTRO, COUNT(CLIENTE) AS NUM_DE_REGISTROS
FROM TB_ACT_RETENCAO_POR_TRIMESTRE
WHERE MES_REGISTRO IS NOT NULL
GROUP BY MES_REGISTRO
ORDER BY NUM_DE_REGISTROS DESC

--CLIENTES QUE DESATIVARAM O PROGRAMA
SELECT * FROM TB_ACT_RETENCAO_POR_MES
WHERE ESTADO_CLIENTE = 'Churned'

